-- 코드를 작성해주세요
SELECT
    A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM 
    ITEM_INFO A
WHERE 
    A.ITEM_ID NOT IN (SELECT IFNULL(PARENT_ITEM_ID,'NONE')
                        FROM ITEM_TREE
                        GROUP BY PARENT_ITEM_ID)
ORDER BY ITEM_ID DESC;





# SELECT
#     A.ITEM_ID, A.ITEM_NAME, A.RARITY
# FROM
#     ITEM_INFO AS A
# JOIN ITEM_TREE AS B
# ON A.ITEM_ID = B.ITEM_ID
# WHERE
#     A.ITEM_ID NOT IN (SELECT IFNULL(PARENT_ITEM_ID,'NONE')
#                     FROM ITEM_INFO
#     ) AND B.PARENT_ITEM_ID IS NOT NULL
# ORDER BY ITEM_ID DESC;