-- 코드를 작성해주세요
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE 
    ITEM_ID NOT IN(
        SELECT PARENT_ITEM_ID
        FROM ITEM_TREE
        WHERE 
            PARENT_ITEM_ID IS NOT NULL
    )
ORDER BY ITEM_ID DESC;









# SELECT
#     A.ITEM_ID, A.ITEM_NAME, A.RARITY
# FROM 
#     ITEM_INFO A
# WHERE 
#     A.ITEM_ID IN (SELECT IFNULL(PARENT_ITEM_ID,'NONE')
#                         FROM ITEM_TREE
#                         GROUP BY PARENT_ITEM_ID)
# ORDER BY ITEM_ID DESC;
