-- 코드를 입력하세요
SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(*) >=2
ORDER BY USER_ID ASC, PRODUCT_ID DESC
;

# SELECT USER_ID, PRODUCT_ID, COUNT(PRODUCT_ID) AS FREQUENCY
# FROM ONLINE_SALE
# ORDER BY USER_ID, PRODUCT_ID








# SELECT USER_ID, PRODUCT_ID,count(*)
# FROM ONLINE_SALE 
# group by USER_ID, PRODUCT_ID
# # having count(*) >=2
# order by USER_ID, PRODUCT_ID desc