-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM 
    REST_INFO
WHERE
        (FOOD_TYPE,FAVORITES) IN (SELECT FOOD_TYPE, MAX(FAVORITES)
            FROM REST_INFO
            GROUP BY FOOD_TYPE)
ORDER BY FOOD_TYPE DESC;









# SELECT 
#     FOOD_TYPE, REST_ID, REST_NAME,  FAVORITES
# FROM 
#     REST_INFO
# WHERE 
#     (FOOD_TYPE, FAVORITES) IN (
#         SELECT FOOD_TYPE, MAX(FAVORITES)
#         FROM REST_INFO
#         GROUP BY FOOD_TYPE
#     )
# ORDER BY 
#     FOOD_TYPE DESC

# 734, 230 ,151,102

# SELECT REST_ID , REST_NAME,	FOOD_TYPE, FAVORITES	 FROM REST_INFO A
# ORDER BY FAVORITES DESC;