-- 코드를 작성해주세요
SELECT B.ID ,
    CASE
        WHEN B.PER <=0.25 THEN 'CRITICAL'
        WHEN B.PER <=0.5 THEN 'HIGH'
        WHEN B.PER <=0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PER
        FROM ECOLI_DATA ) AS B 
ORDER BY ID ASC








# SELECT D.ID,
# CASE
# WHEN D.PER >= 0.75 THEN 'CRITICAL'
# WHEN D.PER >=0.5 THEN 'HIGH'
# WHEN D.PER >=0.25 THEN 'MEDIUM'
# ELSE 'LOW'
# END AS COLONY_NAME
# FROM
# (SELECT ID,
#  PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY) AS PER
#  FROM ECOLI_DATA
# ) AS D
# ORDER BY D.ID;