-- 코드를 작성해주세요
SELECT D.ID, 
CASE
    WHEN D.PER >=0.75 THEN 'CRITICAL'
    WHEN D.PER >=0.50 THEN 'HIGH'
    WHEN D.PER >=0.25 THEN 'MEDIUM'
    ELSE 'LOW'
END AS COLONY_NAME

FROM 
(SELECT ID,
 PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY) AS PER
 FROM ECOLI_DATA 
) AS D
ORDER BY D.ID;