-- 코드를 입력하세요
SELECT LEFT(PRODUCT_CODE,2)  AS CATEGORY, COUNT(*) AS PRODUCT
FROM PRODUCT
GROUP BY CATEGORY
ORDER BY CATEGORY;









# SELECT LEFT(PRODUCT_CODE,2) AS CATEGORY , COUNT(PRODUCT_ID) AS PRODUCTS, PRODUCT_ID
# FROM PRODUCT 
# GROUP BY CATEGORY
# ORDER BY PRODUCT_CODE
# SELECT LEFT(PRODUCT_CODE,2) AS CATEGORY
# FROM PRODUCT
# GROUP BY CATEGORY