-- 코드를 작성해주세요
SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR, (E2.MA - E.SIZE_OF_COLONY) AS YEAR_DEV , E.ID
FROM ECOLI_DATA AS E
JOIN(
    SELECT 
        YEAR(E.DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MA
    FROM ECOLI_DATA E
    GROUP BY YEAR) AS E2

ON E2.YEAR = YEAR(DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV 
;