-- 코드를 작성해주세요
SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO A
WHERE 
    FISH_TYPE IN (
        SELECT FISH_TYPE
        FROM FISH_NAME_INFO
        WHERE 
            FISH_NAME IN ('BASS','SNAPPER')
        )








# SELECT COUNT(*) AS FISH_COUNT 
# FROM FISH_INFO A 
# WHERE A.FISH_TYPE IN (
#     SELECT FISH_TYPE
#     FROM FISH_NAME_INFO B
#     WHERE B.FISH_NAME IN ('BASS','SNAPPER'));
