-- 코드를 입력하세요
SELECT FIRST_HALF.FLAVOR FROM FIRST_HALF
JOIN ICECREAM_INFO 
on FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
where FIRST_HALF.TOTAL_ORDER > 3000 and ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based' ;
